/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.modconf;

import com.videoup.controllers.Controller;
import com.videoup.entities.VideoupBaseEntity;
import com.videoup.entities.VideoupTaxes;
import com.videoup.views.utils.Utils;
import com.videoup.views.utils.ViewFicha;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Pedro
 */
public class CTaxes extends ViewFicha{
    
    private List<Component> taxes;
    private STax tax2Del;

    /**
     * Creates new form CTaxes
     */
    public CTaxes(Controller ctrl, int id) {
        super(ctrl,id,false);
        initComponents();
        initComps();
        tax2Del=null;
    }
    
    private void initComps(){
        putMainContain(mainContain);
        removeObtnNew();
        taxes=new ArrayList<Component>();
        loadEntities();
    }

    private void loadEntities(){
        List<VideoupTaxes> taxs=loadList("from VideoupTaxes", null, 0, false);
        STax tax;
        if(taxs==null){
            showError("Error al cargar datos: "+getError());
            return;
        }
        for(VideoupTaxes oneTax: taxs){
            tax=new STax(this);
            tax.setTaxEntity(oneTax);
            taxes.add(tax);
        }
        refreshTaxes();
    }
    
    private void addNewTax(){
        STax tax=new STax(this);
        taxes.add(tax);
        refreshTaxes();
    }
    
    private void refreshTaxes(){
        pnlTaxes.setVisible(false);
        Utils.loadAsTableLayout(taxes, pnlTaxes, "No hay impuestos agregados");
        pnlTaxes.setVisible(true);
    }
        
    public void deleteATax(STax tax){
        PerformingTask task=new PerformingTask();
        VideoupTaxes ent;
        if(!ctrl.confirm("Eliminar impuesto", "¿En verdad desea borrar el registro de este impuesto?")){
            return;
        }
        ent=tax.getEntity(false);
        if(ent!=null){
            setBusy("Eliminando registro",true);
            task.setTask(3); task.setParam(ent,false);
            tax2Del=tax; validate(); task.execute();
        }else{
            taxes.remove(tax);
            refreshTaxes();
        }
    }
    
    @Override
    protected boolean deleteEntity(VideoupBaseEntity entity){
        boolean deleted=super.deleteEntity(entity);
        if(deleted){
            taxes.remove(tax2Del);
            refreshTaxes();
        }
        return deleted;
    }
    
    @Override
    protected boolean isDataValid(){
        STax tmTax;
        for(Component cmp: taxes){
            if(cmp instanceof STax){
                tmTax=(STax)cmp;
                if(!tmTax.isDataValid()){
                    setError(tmTax.getError());
                    return false;
                }
            }
        }
        return true;
    }
    
    @Override
    protected boolean saveEntity(VideoupBaseEntity ignore,boolean forceAsNew){
        List<VideoupBaseEntity> entities=new ArrayList<VideoupBaseEntity>();
        boolean saved;
        for(Component tax: taxes){
            if(tax instanceof STax){
                entities.add( ((STax)tax).getEntity(true) );
            }
        }
        saved=super.saveEntities(entities);
        return saved;
    }
    
    @Override
    protected void updateIdTitle(){
        lblTitle.setText(getTitle());
        ctrl.changeViewName(this, getTitle());
    }
    
    @Override
    public String getTitle(){
        return "Impuestos aplicables a operaciones";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAddTax = new javax.swing.JButton();
        pnlTaxes = new javax.swing.JPanel();

        mainContain.setLayout(new java.awt.BorderLayout());

        btnAddTax.setText("Agregar nuevo impuesto");
        btnAddTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddTax)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddTax)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainContain.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout pnlTaxesLayout = new javax.swing.GroupLayout(pnlTaxes);
        pnlTaxes.setLayout(pnlTaxesLayout);
        pnlTaxesLayout.setHorizontalGroup(
            pnlTaxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        pnlTaxesLayout.setVerticalGroup(
            pnlTaxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        mainContain.add(pnlTaxes, java.awt.BorderLayout.CENTER);

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaxActionPerformed
        addNewTax();
    }//GEN-LAST:event_btnAddTaxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTax;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainContain;
    private javax.swing.JPanel pnlTaxes;
    // End of variables declaration//GEN-END:variables
}
