/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.modconf;

import java.io.File;
import javax.swing.JComboBox;

/**
 *
 * @author Pedro
 */
public class ImporterImageField extends javax.swing.JPanel {

    private int type; // 1=campo blob de columna, 2=ruta de archivo, 3=desde carpeta
    private int is2Use; // 0=undefined, 1=true, -1=false
    
    /**
     * Creates new form ImporterImageField
     */
    public ImporterImageField(String fieldName,boolean askName) {
        initComponents();
        type=0; is2Use=0;
        lblFieldNAme.setText(fieldName);
        txtName.setEditable(askName);
        txtName.setVisible(askName);
        if(askName){
            lblFieldNAme.setText("Nombre:");
        }
    }

    public void addFieldsItem(String item){
        jcbFields.addItem(item);
        jcbFields2.addItem(item);
    }
    
    public void copyFielsItems(JComboBox jcb){
        int nIts=jcb.getItemCount();
        int cnt;
        jcbFields.removeAllItems();
        jcbFields2.removeAllItems();
        for(cnt=0;cnt<nIts;cnt++){
            jcbFields.addItem(jcb.getItemAt(cnt));
            jcbFields2.addItem(jcb.getItemAt(cnt));
        }
    }
    
    public void addJcombListener(java.awt.event.ItemListener listener){
        jcbFields.addItemListener(listener);
        jcbFields2.addItemListener(listener);
    }
    
    public boolean isReady2Use(){
        if(is2Use==0){
            validate2Use();
        }
        return (is2Use==1);
    }
    
    private void validate2Use(){
        if( (type==1 || type==2) && jcbFields2.getSelectedIndex()>0 ){
            is2Use=1;
        }else if( type==3 && jcbFields.getSelectedIndex()>0 && txtFolder.getText().trim().length()>0 ){
            is2Use=1;
        }else{
            is2Use=-1;
        }
    }
    
    public boolean isNameValid(){
        String name=txtName.getText().trim();
        if(name.length()<7 || name.length()>155){
            return false;
        }
        return true;
    }
    
    public String genInputName(){
        return  txtName.getText().trim();
    }
    
    public int getIndexColumn(){
        if(type==3){
            return jcbFields.getSelectedIndex();
        }else{
            return jcbFields2.getSelectedIndex();
        }
    }
    
    public int getType(){
        return type;
    }
    
    public String getFFPath(String bdValue){
        String[] exts=txtExts.getText().split(", ");
        String path=txtFolder.getText().trim();
        File testExs;
        path+=(path.endsWith(File.separator)?"":File.separator);
        path+=(txtTkn1.getText().trim().length()>0?txtTkn1.getText().trim():"");
        path+=bdValue;
        path+=(txtTkn2.getText().trim().length()>0?txtTkn2.getText().trim():"");
        for(String ext: exts){
            testExs=new File(path+"."+ext);
            if(testExs.isFile()){
                path+="."+ext;
                break;
            }
        }
        return path;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFFolder = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFolder = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTkn1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbFields = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtTkn2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtExts = new javax.swing.JTextField();
        pnlFBD = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jcbFields2 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        lblFieldNAme = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnChangeType = new javax.swing.JButton();
        pnlSelType = new javax.swing.JPanel();
        btnFFolder = new javax.swing.JButton();
        btnFPath = new javax.swing.JButton();
        btnFBlob = new javax.swing.JButton();

        jLabel1.setText("Carpeta:");

        jLabel2.setText("Nombre de archivo:");

        txtTkn1.setToolTipText("Token de texto para formar nombre de archivo");

        jLabel3.setText("+");

        jLabel4.setText("+");

        txtTkn2.setToolTipText("Token de texto para formar nombre de archivo");

        jLabel5.setText("Extenciones:");

        txtExts.setText("jpg, jpeg, png");

        javax.swing.GroupLayout pnlFFolderLayout = new javax.swing.GroupLayout(pnlFFolder);
        pnlFFolder.setLayout(pnlFFolderLayout);
        pnlFFolderLayout.setHorizontalGroup(
            pnlFFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFFolderLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFolder))
            .addGroup(pnlFFolderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTkn1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTkn2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlFFolderLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlFFolderLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtExts, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );
        pnlFFolderLayout.setVerticalGroup(
            pnlFFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFFolderLayout.createSequentialGroup()
                .addGroup(pnlFFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTkn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jcbFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtTkn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtExts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel6.setText("Columna:");

        javax.swing.GroupLayout pnlFBDLayout = new javax.swing.GroupLayout(pnlFBD);
        pnlFBD.setLayout(pnlFBDLayout);
        pnlFBDLayout.setHorizontalGroup(
            pnlFBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFBDLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbFields2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 91, Short.MAX_VALUE))
        );
        pnlFBDLayout.setVerticalGroup(
            pnlFBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(jcbFields2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new java.awt.BorderLayout());

        lblFieldNAme.setText("Nombre Campo");
        jPanel1.add(lblFieldNAme);

        txtName.setColumns(12);
        txtName.setToolTipText("Ingrese el nombre del campo");
        jPanel1.add(txtName);

        btnChangeType.setText("T");
        btnChangeType.setToolTipText("Cambiar tipo de importacion");
        btnChangeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeTypeActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangeType);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        pnlSelType.setLayout(new java.awt.GridLayout(3, 1));

        btnFFolder.setText("Imagenes desde carpeta");
        btnFFolder.setToolTipText("Carga las imagenes desde una carpeta especifica.");
        btnFFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFFolderActionPerformed(evt);
            }
        });
        pnlSelType.add(btnFFolder);

        btnFPath.setText("Ruta a imagen desde BD");
        btnFPath.setToolTipText("Carga cada imagen desde una ruta leida directo desde la BD");
        btnFPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFPathActionPerformed(evt);
            }
        });
        pnlSelType.add(btnFPath);

        btnFBlob.setText("Campo Blob desde BD");
        btnFBlob.setToolTipText("Carga la imagen como datos Blob directo dese la BD");
        btnFBlob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFBlobActionPerformed(evt);
            }
        });
        pnlSelType.add(btnFBlob);

        add(pnlSelType, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFFolderActionPerformed
        setVisible(false);
        remove(pnlSelType);
        add(pnlFFolder);
        setVisible(true);
        type=3;
    }//GEN-LAST:event_btnFFolderActionPerformed

    private void btnFPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFPathActionPerformed
        setVisible(false);
        remove(pnlSelType);
        add(pnlFBD);
        setVisible(true);
        type=2;
    }//GEN-LAST:event_btnFPathActionPerformed

    private void btnFBlobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFBlobActionPerformed
        setVisible(false);
        remove(pnlSelType);
        add(pnlFBD);
        setVisible(true);
    }//GEN-LAST:event_btnFBlobActionPerformed

    private void btnChangeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeTypeActionPerformed
        setVisible(false);
        remove(pnlFBD); remove(pnlFFolder);
        add(pnlSelType);
        setVisible(true);
        type=1;
    }//GEN-LAST:event_btnChangeTypeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeType;
    private javax.swing.JButton btnFBlob;
    private javax.swing.JButton btnFFolder;
    private javax.swing.JButton btnFPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbFields;
    private javax.swing.JComboBox jcbFields2;
    private javax.swing.JLabel lblFieldNAme;
    private javax.swing.JPanel pnlFBD;
    private javax.swing.JPanel pnlFFolder;
    private javax.swing.JPanel pnlSelType;
    private javax.swing.JTextField txtExts;
    private javax.swing.JTextField txtFolder;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTkn1;
    private javax.swing.JTextField txtTkn2;
    // End of variables declaration//GEN-END:variables
}
