/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.modconf;

import com.videoup.controllers.Controller;
import com.videoup.entities.VideoupBaseEntity;
import com.videoup.entities.VideoupLangs;
import com.videoup.views.utils.Utils;
import com.videoup.views.utils.ViewFicha;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Pedro
 */
public class JLang extends ViewFicha{

    private List<VideoupLangs> lsLangs;
    
    /**
     * Creates new form JLang
     */
    public JLang(Controller ctrl, int id) {
        super(ctrl,id,false);
        initComponents();
        initComps();
    }
    
    private void initComps(){
        putMainContain(mainContain);
        removeObtnNew();
        removeObtnSave();
        refreshLangs();
        changes=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btbAddLang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlIdiomas = new javax.swing.JPanel();

        mainContain.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Idiomas disponibles para los articulos");

        btbAddLang.setText("Agregar idioma");
        btbAddLang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbAddLangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btbAddLang)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btbAddLang)))
        );

        mainContain.add(jPanel1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout pnlIdiomasLayout = new javax.swing.GroupLayout(pnlIdiomas);
        pnlIdiomas.setLayout(pnlIdiomasLayout);
        pnlIdiomasLayout.setHorizontalGroup(
            pnlIdiomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        pnlIdiomasLayout.setVerticalGroup(
            pnlIdiomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlIdiomas);

        mainContain.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void btbAddLangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbAddLangActionPerformed
        PerformingTask task;
        JFileChooser selFile=new JFileChooser();
        String[] suffices=ImageIO.getReaderFileSuffixes();
        VideoupLangs lang;
        String nombre;
        File imgfile;
        Image img;
        boolean isImage;
        byte[] blob;
        FileInputStream fileInpStr;
        int slFile;
        nombre=ctrl.askForString("Ingrese el nombre del idioma", "Agregar idioma");
        if(nombre==null){ return; }
        if(nombre.length()<2 || nombre.length()>255){
            ctrl.showDialogErr("El nombre debe tener una longitud entre 2 y 155 caracteres");
            return;
        }
        for(int i=0;i<suffices.length;i++){
            selFile.addChoosableFileFilter(new FileNameExtensionFilter(suffices[i]+" archivos",suffices[i]));
        }
        slFile=selFile.showDialog(ctrl.getMainWindow(),"Elegir imagen");
        if(slFile==JFileChooser.APPROVE_OPTION){
            imgfile=selFile.getSelectedFile();
            isImage=true;
            try{
                img=ImageIO.read(imgfile);
                if(img==null){ isImage=false; }
            }catch(IOException ex){ isImage=false; }
            if(!isImage){
                ctrl.showDialogErr("El archivo deb ser una imagen");
                return;
            }
            blob=new byte[(int)imgfile.length()];
            try {
                fileInpStr=new FileInputStream(imgfile);
                fileInpStr.read(blob);
            }catch (FileNotFoundException ex){
                ctrl.showDialogErr("Error: "+ex.getMessage());
                return;
            }catch (IOException ex){
                ctrl.showDialogErr("Error: "+ex.getMessage());
                return;
            }
            lang=new VideoupLangs(nombre,blob);
            task=new PerformingTask();
            setBusy("Agregando idioma",true);
            task.setTask(2); task.setParam(lang,false);
            validate(); task.execute();
        }
    }//GEN-LAST:event_btbAddLangActionPerformed

    @Override
    protected boolean saveCustom(VideoupBaseEntity entity, boolean asNew){
        boolean saved=super.saveEntity(entity,asNew);
        if(saved){
            lsLangs.add((VideoupLangs)entity);
            refreshLangs();
        }
        return saved;
    }
    
    private void refreshLangs(){
        lsLangs=loadList("from VideoupLangs",null,0,false);
        List<Component> cmpLangs=new ArrayList<Component>();
        for(VideoupLangs lng: lsLangs){
            cmpLangs.add(new SLang(lng,false,this,true,true));
        }
        Utils.loadAsTableLayout(cmpLangs, pnlIdiomas, "No hay idiomas registrados");
    }
    
    @Override
    public String getTitle(){
        return "Idiomas en productos";
    }
    
    @Override
    public void deleteLang(VideoupLangs lng){
        PerformingTask task;
        if(!ctrl.confirm("Va a eliminar un registro", "Esta accion NO se podra deshacer, ¿desea continuar?")){
            return;
        }
        task=new PerformingTask();
        setBusy("Eliminado registro",true);
        task.setTask(3); task.setParam(lng,false);
        validate(); task.execute();
    }
    
    @Override
    protected boolean deleteEntity(VideoupBaseEntity entity){
        boolean deleted=super.deleteEntity(entity);
        if(deleted){
            lsLangs.remove((VideoupLangs)entity);
            refreshLangs();
        }
        return deleted;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbAddLang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainContain;
    private javax.swing.JPanel pnlIdiomas;
    // End of variables declaration//GEN-END:variables
}
