/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.modconf;

import com.hexidec.ekit.EkitCore;
import com.videoup.controllers.CConf;
import com.videoup.controllers.Controller;
import com.videoup.entities.VideoupBaseEntity;
import com.videoup.entities.VideoupConf;
import com.videoup.utils.GenProccess;
import com.videoup.views.utils.ImagePanel;
import com.videoup.views.utils.ViewFicha;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;

/**
 *
 * @author Pedro
 */
public class SConf extends ViewFicha{
    
    private VideoupConf ent;
    private ImagePanel imgLogo;
    private EkitCore jtaCond;
    
    public SConf(Controller ctrl, int id) {
        super(ctrl,id,true);
        initComponents();
        initComps(ent);
    }
    
    private void initComps(Object ent){
        putMainContain(mainContain);
        jtaCond=new EkitCore(false,false,false,false,false,false,false,false,false);
        loadEntity( ((CConf)ctrl).getConfEnt() );
        setUpValidator();
        addJText2ListenChanges(txNomClub);
        addJText2ListenChanges(txDNIDef);
        addJText2ListenChanges(txDNIRegExp);
        addJText2ListenChanges(txPostCodeRegExp);
        jtaCond.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jtaCond.setJDialogIcon(new javax.swing.ImageIcon(getClass().getResource("/com/videoup/imgs/logo.jpg")).getImage());
        pnlContrato.add(jtaCond,BorderLayout.CENTER);
        pnlContrato.add(jtaCond,BorderLayout.CENTER);
        addJText2ListenChanges(jtaCond.getSourcePane());
        removeObtnNew();
        changes=false;
    }

    @Override
    protected void setUpValidator(){
        super.setUpValidator();
        vltor.addStringField(txNomClub, "Nombre del videoclub", true, 3, 55,0);
        vltor.addStringField(txDNIDef, "Nombre de documento de identificacaion del socio", true, 2, 55,0);
        vltor.addStringField(txDNIRegExp, "Expresion regular de valor de identificacion", true, 2, 650,0);
        vltor.addStringField(txPostCodeRegExp, "Expresion regular de cogido postal", true, 2, 650,0);
        vltor.addStringField(jtaCond.getSourcePane(), "Texto de contrato", true, 15, 9999,0);
        vltor.addIntField(txtPgTam, "Tamaño en paginas de listas", true, 5, 759, 0);
        vltor.addIntField(txtMinExtra, "Fraccion minutos en tiempo extra", true, 0, 720, 0);
    }
    
    @Override
    public void loadEntity(Object oEnt){
        ent=((VideoupConf)oEnt);
        txNomClub.setText(ent.getNVclub());
        txDNIDef.setText(ent.getDniDef());
        txDNIRegExp.setText(ent.getDniRgexp());
        txPostCodeRegExp.setText(ent.getPcodeRgexp());
        jtaCond.setDocumentText(ent.getContrato());
        jcbMaxOfrt.setSelectedItem(""+ent.getMaxoffrts());
        txtPgTam.setText(""+ent.getPagesize());
        txtMinExtra.setText(""+ent.getFracMinExtra());
        jckChangEstr.setSelected(ent.getChangeFinEstreno());
        updateLogo();
        changes=false;
    }
    
    protected void loadEntity(int id){
    }
    
    @Override
    protected boolean saveEntity(VideoupBaseEntity ignore,boolean forceAsNew){
        boolean saved;
        ent.setNVclub(txNomClub.getText());
        ent.setDniDef(txDNIDef.getText());
        ent.setDniRgexp(txDNIRegExp.getText());
        ent.setPcodeRgexp(txPostCodeRegExp.getText());
        ent.setContrato(jtaCond.getDocumentBody());
        ent.setMaxoffrts( Integer.parseInt(jcbMaxOfrt.getSelectedItem().toString()) );
        ent.setPagesize( Integer.parseInt(txtPgTam.getText()) );
        ent.setFracMinExtra( Integer.parseInt(txtMinExtra.getText()) );
        ent.setChangeFinEstreno(jckChangEstr.isSelected());
        saved=super.saveEntity(ent,forceAsNew);
        changes=!saved;
        return saved;
    }
    
    @Override
    public String getTitle(){
        return "Configuracion del sistema";
    }
        
    @Override
    protected void updateIdTitle(){
        //setId(ent.getIdcc());
        lblTitle.setText(getTitle());
        ctrl.changeViewName(this, getTitle());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txNomClub = new javax.swing.JTextField();
        txDNIDef = new javax.swing.JTextField();
        txDNIRegExp = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        txPostCodeRegExp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbMaxOfrt = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        btnSelectLogo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPgTam = new javax.swing.JTextField();
        pnlContrato = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jckChangEstr = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtMinExtra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblImgError = new javax.swing.JLabel();

        jLabel2.setText("Documento de identificacion del socio:");

        jLabel3.setText("Expresion regular de valor de identificacion:");

        jLabel4.setText("Nombre del videoclub:");

        txNomClub.setColumns(21);

        txDNIDef.setColumns(21);

        txDNIRegExp.setColumns(21);

        label.setText("Expresion regular de codigo postal:");

        txPostCodeRegExp.setColumns(21);

        jLabel1.setText("Texto de contrato al afiliar un nuevo socio:");

        jLabel5.setText("Numero maximo de ofertas por renta:");

        jcbMaxOfrt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" }));

        jLabel6.setText("(Para casos de ofertas concurrentes)");

        pnlLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlLogo.setLayout(new java.awt.BorderLayout());

        btnSelectLogo.setText("Logo");
        btnSelectLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectLogoActionPerformed(evt);
            }
        });

        jLabel7.setText("Numero de registros por pagina en listas:");

        txtPgTam.setColumns(5);

        pnlContrato.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(197, 113));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Use los tokens:\n\nDatos de empresa:\n[vclub] Nombre del videoclub\n\nOtros: \n[today] Fecha atual\n\nDatos del socio:\n[nomsc] Nombre\n[appsc] Apellidos \n[dnisc] DNI \n[dirsc] Direccion\n[poblsc] Poblacion\n[provsc] Provincia\n[cddsc] Ciudad\n[cpsc] CP \n[mailsc] Correo electronio\n[telcasasc] Telefono de casa\n[telmovsc] Telefono movil\n[codesc] Codigo de socio\n[altasc] Fecha de alta\n[vignsc] Fecha de vigencia\n[replstsc] Representantelst\n ** Todos los representantes \n   en listado vertical\n[repssc] Representantes\n ** Todos los representantes \n   en listado horizontal");
        jScrollPane1.setViewportView(jTextArea1);

        pnlContrato.add(jScrollPane1, java.awt.BorderLayout.LINE_END);

        jckChangEstr.setText("Costo alquiler estrenos a normal automatico");

        jLabel8.setText("Cobrar tiempo extra en fracciones de minutos");

        txtMinExtra.setColumns(5);

        jLabel9.setText("(0 indica no fraccionar)");

        javax.swing.GroupLayout mainContainLayout = new javax.swing.GroupLayout(mainContain);
        mainContain.setLayout(mainContainLayout);
        mainContainLayout.setHorizontalGroup(
            mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainContainLayout.createSequentialGroup()
                        .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(label)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainContainLayout.createSequentialGroup()
                                .addComponent(txNomClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(btnSelectLogo))
                            .addGroup(mainContainLayout.createSequentialGroup()
                                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainContainLayout.createSequentialGroup()
                                        .addComponent(jcbMaxOfrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addComponent(txPostCodeRegExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txDNIDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txDNIRegExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPgTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainContainLayout.createSequentialGroup()
                                        .addComponent(txtMinExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainContainLayout.createSequentialGroup()
                        .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jckChangEstr)
                            .addGroup(mainContainLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainContainLayout.setVerticalGroup(
            mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainContainLayout.createSequentialGroup()
                        .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txNomClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txDNIDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txDNIRegExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label)
                            .addComponent(txPostCodeRegExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcbMaxOfrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(btnSelectLogo)
                    .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPgTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMinExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jckChangEstr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblImgError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblImgError.setForeground(new java.awt.Color(173, 0, 0));
        lblImgError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgError.setText("Error");

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectLogoActionPerformed
        byte[] blob=GenProccess.getImageBlob(ctrl.getMainWindow(),"Elegir imagen");
        if(blob==null){
            ctrl.showDialogErr(GenProccess.getError());
        }else if(blob.length>0){
            ent.setLogoVclub(blob);
            changes=true;
            updateLogo();
        }
    }//GEN-LAST:event_btnSelectLogoActionPerformed
    
    private void updateLogo(){
        InputStream inpstr;
        BufferedImage bfImg;
        if(ent.getLogoVclub()==null){
            return;
        }
        inpstr=new ByteArrayInputStream(ent.getLogoVclub());
        try {
            bfImg = ImageIO.read(inpstr);
        }catch (IOException ex) {
            lblImgError.setText("Error: "+ex.getMessage());
            pnlLogo.add(lblImgError,BorderLayout.CENTER);
            return;
        }
        if(imgLogo!=null){
            pnlLogo.remove(imgLogo);
        }
        imgLogo=new ImagePanel(bfImg,new Dimension(143,189));
        pnlLogo.add(imgLogo,BorderLayout.CENTER);
        validate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox jcbMaxOfrt;
    private javax.swing.JCheckBox jckChangEstr;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblImgError;
    private javax.swing.JPanel mainContain;
    private javax.swing.JPanel pnlContrato;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JTextField txDNIDef;
    private javax.swing.JTextField txDNIRegExp;
    private javax.swing.JTextField txNomClub;
    private javax.swing.JTextField txPostCodeRegExp;
    private javax.swing.JTextField txtMinExtra;
    private javax.swing.JTextField txtPgTam;
    // End of variables declaration//GEN-END:variables
}
