/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.utils;

import com.videoup.entities.VideoupBcdlang;
import com.videoup.entities.VideoupLangs;
import com.videoup.utils.GeneralDAO;
import com.videoup.views.modconf.SLang;
import com.videoup.views.modmovs.MvGmCopy;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Pedro
 */
public class ChooseLangs extends javax.swing.JDialog {

    private MvGmCopy frm;
    private boolean asLang;
    private List<Component> cmpLangs;
    
    /**
     * Creates new form ChooseLangs
     */
    public ChooseLangs(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        frm=null;
        asLang=true;
        initComponents();
        setSize(363,433);
        setLocationRelativeTo(parent);
    }

    private void loadLangs(String exclude){
        GeneralDAO genDao=new GeneralDAO();
        List<VideoupLangs> lsLangs=genDao.getListEntities("from VideoupLangs "+exclude,null,0, false);
        cmpLangs=new ArrayList<Component>();
        for(VideoupLangs lng: lsLangs){
            cmpLangs.add(new SLang(lng,true,null,true,false));
        }
        Utils.loadAsTableLayout(cmpLangs, pnlList, "No hay idiomas registrados");
    }
    
    private String excludeLangs(List<VideoupBcdlang> exLangs, boolean asLang){
        String exc="";
        if(!exLangs.isEmpty()){
            for(VideoupBcdlang rel: exLangs){
                if(rel.getAsLang()==asLang){
                    exc+=(exc.length()>0?" and ":"")+"idit<>"+rel.getIdit().getIdit();
                }
            }
        }
        if(exc.length()>0){
            exc="where ("+exc+")";
        }
        return exc;
    }
    
    private void setSelectedLangs(){
        List<VideoupLangs> selecteds=new ArrayList<VideoupLangs>();
        for(Component cmp: cmpLangs){
            if( ((SLang)cmp).isSelected() ){
                selecteds.add( ((SLang)cmp).getEntity() );
            }
        }
        dispose();
        frm.addLangs(selecteds, asLang);
    }
    
    public void setCallinForm(MvGmCopy frm, boolean asLang,List<VideoupBcdlang> lsLangs){
        this.frm=frm;
        this.asLang=asLang;
        loadLangs( excludeLangs(lsLangs,asLang) );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Elegir idiomas");
        setAlwaysOnTop(true);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar seleccionados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout pnlListLayout = new javax.swing.GroupLayout(pnlList);
        pnlList.setLayout(pnlListLayout);
        pnlListLayout.setHorizontalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        pnlListLayout.setVerticalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlList);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setSelectedLangs();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlList;
    // End of variables declaration//GEN-END:variables
}
