/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.utils;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Pedro
 */
public class JRoundPanel extends javax.swing.JPanel {

    private int radio1;
    private int radio2;

    public int getRadio1() {
        return radio1;
    }

    public int getRadio2() {
        return radio2;
    }

    public void setRadio1(int radio1) {
        this.radio1 = radio1;
    }

    public void setRadio2(int radio2) {
        this.radio2 = radio2;
    }
    
    public JRoundPanel(){
        super();
        radio1=27;
        radio2=27;
        setBackground(new java.awt.Color(167, 182, 193));
    }
    
    /**
     * Creates new form JRoundPanel
     */
    public JRoundPanel(int r1, int r2) {
        super();
	radio1=r1; radio2=r2; setOpaque(false);
        setBackground(new java.awt.Color(167, 182, 193));
    }
    
    @Override
    protected void paintComponent(Graphics g) {
      Graphics2D g2 = (Graphics2D) g;
      g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);			            
      Paint oldPaint = g2.getPaint();
      RoundRectangle2D.Float r2d = new RoundRectangle2D.Float(0,0,getWidth()-1,getHeight()-1,radio1,radio2);
      g2.clip(r2d);
      g2.fillRect(0,0,getWidth(),getHeight());
      g2.drawRoundRect(0, 0, getWidth()-2 , getHeight() -2, 18, 18);
      g2.setPaint(oldPaint);
      super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(167, 182, 193));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
