/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.utils;

import com.videoup.controllers.Controller;
import com.videoup.entities.VideoupBaseEntity;
import com.videoup.entities.VideoupTagitems;
import com.videoup.entities.VideoupTags;
import com.videoup.utils.GenProccess;
import com.videoup.views.modconf.BarCode;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.TreeMap;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Pedro
 */
public class TagEditor extends javax.swing.JPanel implements DocumentListener {
    
    private TreeMap<Integer, JButton> btns;
    private boolean locked;
    private boolean lockGSize;
    private TagSingle tag;
    private int counter;
    private int current;
    private Controller ctrl;
    private byte[] blob;
    private VideoupTags ent;
    private String error;
    private BarCode parent;
    private boolean isMemberTag;
    
    /**
     * Creates new form TagEditor
     */
    public TagEditor(BarCode parent, Controller ctrl, VideoupTags vtag, boolean isMemberTag) {
        this.ctrl=ctrl;
        this.parent=parent;
        ent=vtag;
        initComponents();
        counter=0; tag=new TagSingle(); locked=false;
        jpnTag.add(tag); btns=new TreeMap<Integer, JButton>();
        jtxTx.getDocument().addDocumentListener(this);
        jtxCode.getDocument().addDocumentListener(this);
        this.isMemberTag=isMemberTag;
        if(isMemberTag){
            jcbField.removeAllItems();
            jcbField.addItem("Nombre");
            jcbField.addItem("Apellidos");
            jcbField.addItem("DNI");
            jcbField.addItem("Codigo de socio");
            jcbField.addItem("Direccion");
            jcbField.addItem("CP");
            jcbField.addItem("Ciudad");
            jcbField.addItem("Provincia");
            jcbField.addItem("Poblacion");
            jcbField.addItem("Telefono casa");
            jcbField.addItem("Telefono movil");
            jcbField.addItem("Alta");
            jcbField.addItem("Vigencia");
            jcbField.addItem("Foto");
        }
        loadTag();
    }

    private void loadTag(){        
        ItemTag itmn;
        JButton btn;
        lockGSize=true;
        jspinWidth.setValue(ent.getWidth());
        jspinHeight.setValue(ent.getHeight());
        lockGSize=false;
        resizeTag();
        for(VideoupTagitems itTg: ent.getVideoupTagitemsList()){
            counter++; current=counter;
            itmn=new ItemTag(itTg);
            btn=new JButton(itTg.getTitle());
            btn.setActionCommand(""+current);
            btn.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent eve){ standOut(eve,0); }
            });
            btns.put(current, btn); tag.addNewItem(current,itmn);
            pnlMenuItems.setVisible(false); pnlMenuItems.add(btn); pnlMenuItems.setVisible(true);
            standOut(null,current);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        pnlMenuItems = new javax.swing.JPanel();
        btnAddItem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jpnTag = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jspinWidth = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jspinHeight = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jcbType = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jtxTx = new javax.swing.JTextField();
        jbtnImg = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcbCode = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jtxCode = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jspinWidth1 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jspinHeight1 = new javax.swing.JSpinner();
        btnReleaseItem = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblField = new javax.swing.JLabel();
        jcbField = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(338);

        jPanel5.setLayout(new java.awt.BorderLayout());

        pnlMenuItems.setBorder(javax.swing.BorderFactory.createTitledBorder("Componentes"));
        pnlMenuItems.setLayout(new javax.swing.BoxLayout(pnlMenuItems, javax.swing.BoxLayout.Y_AXIS));

        btnAddItem.setText("Agregar nuevo");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });
        pnlMenuItems.add(btnAddItem);

        jPanel5.add(pnlMenuItems, java.awt.BorderLayout.LINE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vista previa"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jpnTag.setBackground(new java.awt.Color(255, 255, 255));
        jpnTag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 19, 19)));
        jpnTag.setDoubleBuffered(false);
        jpnTag.setLayout(new java.awt.GridBagLayout());
        jPanel2.add(jpnTag, new java.awt.GridBagConstraints());

        jPanel5.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamaño de etiqueta"));

        jLabel7.setText("Ancho:");
        jPanel3.add(jLabel7);

        jspinWidth.setModel(new javax.swing.SpinnerNumberModel(80, 0, 205, 1));
        jspinWidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspinWidthStateChanged(evt);
            }
        });
        jPanel3.add(jspinWidth);

        jLabel8.setText("mm  Alto:");
        jPanel3.add(jLabel8);

        jspinHeight.setModel(new javax.swing.SpinnerNumberModel(40, 0, 270, 1));
        jspinHeight.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspinHeightStateChanged(evt);
            }
        });
        jPanel3.add(jspinHeight);

        jLabel13.setText("mm");
        jPanel3.add(jLabel13);

        jPanel5.add(jPanel3, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(jPanel5);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar elemento seleccionado"));

        jLabel4.setText("Tipo de elemento:");

        jcbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Texto", "Codigo de barras", "Imagen", "Campo" }));
        jcbType.setEnabled(false);
        jcbType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTypeItemStateChanged(evt);
            }
        });

        jLabel5.setText("Ingrese texto:");

        jtxTx.setEditable(false);

        jbtnImg.setText("Seleccione Imagen");
        jbtnImg.setEnabled(false);
        jbtnImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImgActionPerformed(evt);
            }
        });

        jLabel6.setText("Estandar codigo:");

        jcbCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Code 128", "Code 39", "Codabar", "EAN-13", "EAN-8", "intl2of5", "EAN-128", "Royal-mail-cbc", "ITF-14", "DataMatrix", "PDF 417", "UPC-A", "UPC-E", "Usps4cb" }));
        jcbCode.setEnabled(false);
        jcbCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCodeItemStateChanged(evt);
            }
        });

        jLabel9.setText("Muestra codigo:");

        jtxCode.setEditable(false);

        btnDelete.setText("Eliminar este elemento");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Posicion del elemento:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(5, 0, 195, 1));
        jSpinner1.setEnabled(false);
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jLabel2.setText("Top:");

        jLabel3.setText("mm   Left:");

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(6, 0, 265, 1));
        jSpinner2.setEnabled(false);
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        jLabel12.setText("Tamaño del elemento:");

        jLabel10.setText("Ancho:");

        jspinWidth1.setModel(new javax.swing.SpinnerNumberModel(30, 0, 190, 1));
        jspinWidth1.setEnabled(false);
        jspinWidth1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspinWidth1StateChanged(evt);
            }
        });

        jLabel11.setText("mm   Alto:");

        jspinHeight1.setModel(new javax.swing.SpinnerNumberModel(19, 0, 250, 1));
        jspinHeight1.setEnabled(false);
        jspinHeight1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspinHeight1StateChanged(evt);
            }
        });

        btnReleaseItem.setText("Liberar");
        btnReleaseItem.setEnabled(false);
        btnReleaseItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReleaseItemActionPerformed(evt);
            }
        });

        jLabel14.setText("mm");

        jLabel15.setText("mm");

        lblField.setText("Campo del registro:");

        jcbField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Titulo", "Genero", "Categoria", "Formato" }));
        jcbField.setEnabled(false);
        jcbField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbFieldItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(btnReleaseItem)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(lblField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jbtnImg)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jtxTx, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(118, 118, 118))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15))
                                            .addComponent(jtxCode)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnDelete)
                                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jspinWidth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel11)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jspinHeight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14)))))
                                .addContainerGap())))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnReleaseItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblField)
                    .addComponent(jcbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jspinWidth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jspinHeight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addGap(175, 175, 175))
        );

        jScrollPane2.setViewportView(jPanel7);

        jSplitPane1.setRightComponent(jScrollPane2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        String namen=JOptionPane.showInputDialog(this.getTopLevelAncestor(), "Nombre del nuevo elemento", "Crear elemento", JOptionPane.QUESTION_MESSAGE);
        if(namen==null){ return; }
        if(namen.trim().equals("") || namen.length()>10){
            JOptionPane.showMessageDialog(this.getTopLevelAncestor(), "Longitud de nombre invalida"); return;
        }
        if(hasItemName(namen)){
            JOptionPane.showMessageDialog(this.getTopLevelAncestor(), "Ya existe nombre: "+namen); return;
        }
        counter++; current=counter;
        ItemTag itmn=new ItemTag(namen, new Dimension(30,19), new Point(5,6));
        JButton btn=new JButton(namen);
        btn.setActionCommand(""+current);
        btn.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent eve){ standOut(eve,0); }
        });
        btns.put(current, btn); tag.addNewItem(current,itmn);
        pnlMenuItems.setVisible(false); pnlMenuItems.add(btn); pnlMenuItems.setVisible(true);
        standOut(null,current);
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void jspinWidthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspinWidthStateChanged
        resizeTag();
    }//GEN-LAST:event_jspinWidthStateChanged

    private void resizeTag(){
        int wd=Integer.parseInt(jspinWidth.getValue().toString());
        int hg=Integer.parseInt(jspinHeight.getValue().toString());
        if(lockGSize){ return; }
        ent.setWidth(wd); ent.setHeight(hg);
        jpnTag.setVisible(false); tag.setDimMM(wd, hg);
        Dimension dim=new Dimension(mm2pixels(wd),mm2pixels(hg));
        tag.setPreferredSize(dim); tag.setMaximumSize(dim); tag.setMinimumSize(dim);
        jpnTag.setVisible(true); validate();
    }
    
    public int mm2pixels(int mm){
        int dpi=72; //getToolkit().getScreenResolution();
        double fact=dpi/25.4f;
        return (int)(mm*fact);
    }
    
    private void standOut(ActionEvent eve, int val){
        if(eve!=null){ current=Integer.parseInt(eve.getActionCommand()); }
        else{ current=val; }
        ItemTag itmn=tag.getItem(current);
        tag.setVisible(false); tag.standOut(current);
        setEditingTag(itmn); tag.setVisible(true);
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar: "+itmn.getTitle()));
    }
    
    private void setEditingTag(ItemTag itag){
        locked=true;
        if(itag!=null){ 
            int tosel=(itag.getType()-1);
            tosel=(tosel>=3?3:tosel);
            btnReleaseItem.setEnabled(true);
            jcbType.setSelectedIndex(-1);
            jcbType.setSelectedIndex(tosel);
            jcbType.setEnabled(true);
            jtxTx.setText(itag.getText());
            jcbCode.setSelectedItem(itag.getBcType());
            jtxCode.setText(itag.getBcValue());
            jspinWidth1.setValue(itag.getDim().width);
            jspinHeight1.setValue(itag.getDim().height);
            jspinWidth1.setEnabled(true); jspinHeight1.setEnabled(true);
            jSpinner1.setValue(itag.getLocation().y);
            jSpinner2.setValue(itag.getLocation().x);
            jSpinner1.setEnabled(true); jSpinner2.setEnabled(true);
            btnDelete.setEnabled(true);
        }else{
            jcbType.setSelectedIndex(-1); jcbType.setEnabled(false);
            jtxTx.setText(""); jtxTx.setEditable(false);
            jcbCode.setSelectedItem(-1); btnReleaseItem.setEnabled(false);
            jtxCode.setText(""); jtxCode.setEditable(false);
            jspinWidth1.setValue(0); jspinHeight1.setValue(0);
            jspinWidth1.setEnabled(false); jspinHeight1.setEnabled(false);
            jSpinner1.setValue(0); jSpinner2.setValue(0);
            jSpinner1.setEnabled(false); jSpinner2.setEnabled(false);
            jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar"));
            jcbCode.setEnabled(false); jbtnImg.setEnabled(false);
            btnDelete.setEnabled(false);
            jcbField.setEnabled(false);
        }
        locked=false;
    }
    
    public boolean hasItemName(String name){
        return tag.existsItem(name);
    }
    
    private void jspinHeightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspinHeightStateChanged
        resizeTag();
    }//GEN-LAST:event_jspinHeightStateChanged

    private void jcbTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTypeItemStateChanged
        int opc=jcbType.getSelectedIndex();
        if(opc==0){
            jtxTx.setEditable(true); jcbField.setEnabled(false);
            jbtnImg.setEnabled(false); jcbCode.setEnabled(false); jtxCode.setEditable(false);
        }else if(opc==2){
            jtxTx.setEditable(false); jcbField.setEnabled(false);
            jbtnImg.setEnabled(true); jcbCode.setEnabled(false); jtxCode.setEditable(false);
        }else if(opc==1){
            jtxTx.setEditable(false); jbtnImg.setEnabled(false);
            jcbCode.setEnabled(true); jtxCode.setEditable(true);
            jcbField.setEnabled(false);
        }else if(opc==3){
            jtxTx.setEditable(false); jbtnImg.setEnabled(false);
            jcbCode.setEnabled(false); jtxCode.setEditable(false);
            jcbField.setEnabled(true);
        }
        updatePreview();
    }//GEN-LAST:event_jcbTypeItemStateChanged

    public boolean isValidTagItems(){
        boolean valid=tag.validateItems();
        if(!valid){ error=tag.getError(); }
        return valid;
    }
    
    public String getError(){
        return error;
    }
    
    public ArrayList<VideoupBaseEntity> getEntities(){
        ArrayList<VideoupBaseEntity> ents;
        ents=tag.getEntities();
        for(VideoupBaseEntity itm: ents){
            ((VideoupTagitems)itm).setIdtg(ent);
            ent.addVideoupTagitems( ((VideoupTagitems)itm) );
        }
        ents.add(ent);
        return ents;
    }
    
    private void jbtnImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImgActionPerformed
        blob=GenProccess.getImageBlob(ctrl.getMainWindow(),"Elegir imagen");
        if(blob==null){
            ctrl.showDialogErr(GenProccess.getError());
        }else if(blob.length>0){
            updatePreview();
        }
    }//GEN-LAST:event_jbtnImgActionPerformed

    private void jcbCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCodeItemStateChanged
        updatePreview();
    }//GEN-LAST:event_jcbCodeItemStateChanged

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        VideoupTagitems vti;
        if(current>0){
            vti=tag.getVideoupTagItem(current);
            parent.deleteTagItem(vti,ent.getIdtg());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void removeItemTag(){
        JButton btn;
        btn=btns.get(current);
        tag.removeItem(current);
        pnlMenuItems.remove(btn);
        btns.remove(current);
        btn=null;
        setEditingTag(null);
        validate();
    }
    
    private void relocateItem(){
        if(current>0 && !locked){
            int top=Integer.parseInt(jSpinner1.getValue().toString());
            int left=Integer.parseInt(jSpinner2.getValue().toString());
            tag.relocateItem(current, new Point(left,top));
        }
    }
    
    private void reSizeItem(){
        if(current>0 && !locked){
            int wd=Integer.parseInt(jspinWidth1.getValue().toString());
            int hg=Integer.parseInt(jspinHeight1.getValue().toString());
            tag.reSizeItem(current, new Dimension(wd,hg));
        }
    }
    
    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        relocateItem();
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        relocateItem();
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jspinWidth1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspinWidth1StateChanged
        reSizeItem();
    }//GEN-LAST:event_jspinWidth1StateChanged

    private void jspinHeight1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspinHeight1StateChanged
        reSizeItem();
    }//GEN-LAST:event_jspinHeight1StateChanged

    private void btnReleaseItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReleaseItemActionPerformed
        tag.standOut(-1); setEditingTag(null); current=-1;
    }//GEN-LAST:event_btnReleaseItemActionPerformed

    private void jcbFieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbFieldItemStateChanged
        updatePreview();
    }//GEN-LAST:event_jcbFieldItemStateChanged

    private void updatePreview(){
        int tpe;
        int tpfield;
        String tx="";
        ItemTag imtt=null;
        if(current>0 && !locked){
            tpe=jcbType.getSelectedIndex();
            int wd=Integer.parseInt(jspinWidth1.getValue().toString());
            int hg=Integer.parseInt(jspinHeight1.getValue().toString());
            int lx=Integer.parseInt(jSpinner2.getValue().toString());
            int ly=Integer.parseInt(jSpinner1.getValue().toString());
            if(tpe==0){
                imtt=new ItemTag("it"+current,jtxTx.getText(),new Dimension(wd,hg),new Point(lx,ly));
            }else if(tpe==2){
                imtt=new ItemTag("it"+current,blob,new Dimension(wd,hg),new Point(lx,ly));
            }else if(tpe==1){
                String tpcode=(jcbCode.getSelectedItem()!=null?jcbCode.getSelectedItem().toString():"null");
                imtt=new ItemTag("it"+current,tpcode,jtxCode.getText(),new Dimension(wd,hg),new Point(lx,ly));
            }else if(tpe==3){
                tpfield=jcbField.getSelectedIndex()+(isMemberTag?8:4);
                if(tpfield==4){ tx="Titulo"; } else if(tpfield==5){ tx="Genero"; }
                else if(tpfield==6){ tx="Categoria"; } else if(tpfield==7){ tx="Formato"; }
                else if(tpfield==8){ tx="Nombre"; } else if(tpfield==9){ tx="Apellidos"; }
                else if(tpfield==10){ tx="DNI"; } else if(tpfield==11){ tx="Codigo Socio"; }
                else if(tpfield==12){ tx="Direccion"; } else if(tpfield==13){ tx="CP"; }
                else if(tpfield==14){ tx="Ciudad"; } else if(tpfield==15){ tx="Provincia"; }
                else if(tpfield==16){ tx="Poblacion"; } else if(tpfield==17){ tx="Telefono Casa"; }
                else if(tpfield==18){ tx="Telefono movil"; } else if(tpfield==19){ tx="Fecha Alta"; }
                else if(tpfield==20){ tx="Fecha vigencia"; } else if(tpfield==21){ tx="Foto"; }
                imtt=new ItemTag("it"+current,tx,new Dimension(wd,hg),new Point(lx,ly));
                imtt.setType(tpfield);
            }
            if(imtt!=null){ tag.updateItem(current, imtt); }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReleaseItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jbtnImg;
    private javax.swing.JComboBox jcbCode;
    private javax.swing.JComboBox jcbField;
    private javax.swing.JComboBox jcbType;
    private javax.swing.JPanel jpnTag;
    private javax.swing.JSpinner jspinHeight;
    private javax.swing.JSpinner jspinHeight1;
    private javax.swing.JSpinner jspinWidth;
    private javax.swing.JSpinner jspinWidth1;
    private javax.swing.JTextField jtxCode;
    private javax.swing.JTextField jtxTx;
    private javax.swing.JLabel lblField;
    private javax.swing.JPanel pnlMenuItems;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) { updatePreview(); }

    @Override
    public void removeUpdate(DocumentEvent e) { updatePreview(); }

    @Override
    public void changedUpdate(DocumentEvent e) { updatePreview(); }
}
