/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.utils;

import com.videoup.controllers.Controller;
import java.awt.BorderLayout;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.SwingWorker;

/**
 *
 * @author Pedro
 */
public class ViewReport extends View{
    
    private String tit;
    protected boolean rdy2Print;

    /**
     * Creates new form ViewReport
     */
    public ViewReport(Controller ctrl, int id, String tit) {
        super(ctrl,id);
        this.tit=tit;
        initComponents();
        initComps();
        rdy2Print=false;
    }
    
    private void initComps(){
        updateTitle();
    }

    protected void setCtrlPanel(JPanel ctrlp){
        pnlCenter.add(ctrlp,BorderLayout.NORTH);
    }
    
    protected void setContentPanel(JPanel contnt){
        pnlCenter.add(contnt,BorderLayout.CENTER);
        add(pnlCenter,BorderLayout.CENTER);
        add(pnlNorth,BorderLayout.NORTH);   
        validate();
    }
    
    private void print(){
        if(rdy2Print){
            printNow();
        }else{
            ctrl.showDialogErr("Reporte vacio");
        }
    }
    
    public void showPrintButton(boolean show){
        btnPrint.setEnabled(show);
        btnPrint.setVisible(show);
    }
    
    protected void printNow(){
        System.out.println("Codificar printNow");
    }
    
    protected boolean validateInput(){
        error="Codificar validateInput";
        return false;
    }
    
    public void insertNullBCode(String bcode, boolean replace){
        System.out.println("Implement insertNullBCode");
    }
    
    protected void generate(){
        System.out.println("Codificar generate");
    }
    
    protected String fmtDate(Date dte){
        Calendar cal=Calendar.getInstance();
        cal.setTime(dte);
        return cal.get(Calendar.YEAR)+"-"+(cal.get(Calendar.MONTH)+1)+"-"+cal.get(Calendar.DATE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jxbLbl = new org.jdesktop.swingx.JXBusyLabel();
        pnlNorth = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnVSel = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnGen = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();

        jxbLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jxbLbl.setText("Generando");
        jxbLbl.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N

        setLayout(new java.awt.BorderLayout());

        pnlNorth.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));
        pnlNorth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 6, 3));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Title");
        pnlNorth.add(lblTitle);

        btnVSel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/videoup/imgs/menu.png"))); // NOI18N
        btnVSel.setToolTipText("Vistas abiertas");
        btnVSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVSelActionPerformed(evt);
            }
        });
        pnlNorth.add(btnVSel);

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/videoup/imgs/print.png"))); // NOI18N
        btnPrint.setToolTipText("Imprimir reporte");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        pnlNorth.add(btnPrint);

        btnGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/videoup/imgs/generate.png"))); // NOI18N
        btnGen.setToolTipText("Generar reporte");
        btnGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenActionPerformed(evt);
            }
        });
        pnlNorth.add(btnGen);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/videoup/imgs/close.png"))); // NOI18N
        btnClose.setToolTipText("Cerrar listado");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnlNorth.add(btnClose);

        add(pnlNorth, java.awt.BorderLayout.NORTH);

        pnlCenter.setLayout(new java.awt.BorderLayout());
        add(pnlCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    protected void setBusy(boolean busy, String message){
        this.setVisible(false);
        jxbLbl.setText(message);
        if(busy){
            remove(pnlNorth);
            remove(pnlCenter);
            add(jxbLbl,BorderLayout.CENTER);
            jxbLbl.setBusy(true);
        }else{
            jxbLbl.setBusy(false);
            remove(jxbLbl);
            add(pnlCenter,BorderLayout.CENTER);
            add(pnlNorth,BorderLayout.NORTH);
        }
        this.setVisible(true);
    }
    
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        closeMe();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenActionPerformed
        LoadingTask task=new LoadingTask();
        setBusy(true,"Generando reporte");
        task.execute();
    }//GEN-LAST:event_btnGenActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        print();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnVSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVSelActionPerformed
        ctrl.goToViewsSel();
    }//GEN-LAST:event_btnVSelActionPerformed

    protected void updateTitle(){
        lblTitle.setText(tit);
        ctrl.changeViewName(this,tit);
    }
        
    @Override
    public String getTitle(){
        return tit;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    protected javax.swing.JButton btnGen;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnVSel;
    private org.jdesktop.swingx.JXBusyLabel jxbLbl;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlCenter;
    protected javax.swing.JPanel pnlNorth;
    // End of variables declaration//GEN-END:variables

    protected class LoadingTask extends SwingWorker<Void, Void>{
        @Override
        protected Void doInBackground() throws Exception{   
            if( !validateInput() ){
                ctrl.showDialogErr(getError());
            }else{
                try{
                    generate();
                }catch(Exception e){ 
                    //e.printStackTrace(); 
                }
            }
            return null;
        }
        @Override
        protected void done() { setBusy(false,"....."); }
    }
}
