/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.modcatgs;

import com.videoup.controllers.Controller;
import com.videoup.entities.VideoupBaseEntity;
import com.videoup.entities.VideoupCatgs;
import com.videoup.views.utils.ViewFicha;

/**
 *
 * @author Pedro
 */
public class Ficha extends ViewFicha{

    private VideoupCatgs ent;
    
    /**
     * Creates new form Ficha
     */
    public Ficha(Controller ctrl, int id) {
        super(ctrl,id, true);
        initComponents();
        initComps(ent);
    }

    public Ficha(Controller ctrl, Object ent, int id) {
        super(ctrl,id,false);
        initComponents();
        initComps(ent);
    }
    
    @Override
    protected void loadEntity(int id){
        ent=(VideoupCatgs)getEntity("from VideoupCatgs where idcg="+id);
    }
    
    private void initComps(Object ent){
        putMainContain(mainContain);
        if(ent==null){
            this.ent=new VideoupCatgs();
        }else{
            loadEntity(ent);
        }
        setUpValidator();
        addJText2ListenChanges(txCatg);
        addJText2ListenChanges(txDesc);
        addJText2ListenChanges(txConds);
    }
    
    @Override
    protected void setUpValidator(){
        super.setUpValidator();
        vltor.addStringField(txCatg, "Nombre de genero", true, 3, 155,0);
        vltor.addStringField(txDesc, "Descripcion", false, 5, 255,0);
        vltor.addStringField(txConds, "Condiciones de uso", false, 10, 1099,0);
    }
    
    @Override
    public String getTitle(){
        return "Ficha de genero"+(getId()==0?" nueva":(ent==null?" ID: "+getId():": "+ent.getCatg()));
    }
    
    @Override
    protected boolean saveEntity(VideoupBaseEntity ignore,boolean forceAsNew){
        boolean saved;
        ent.setCatg(txCatg.getText());
        ent.setDcatg(txDesc.getText());
        ent.setCondTx(txConds.getText());
        saved=super.saveEntity(ent,forceAsNew);
        changes=!saved;
        return saved;
    }
    
    @Override
    protected void updateIdTitle(){
        setId(ent.getIdcg());
        lblTitle.setText(getTitle());
        ctrl.changeViewName(this, getTitle());
    }
    
    @Override
    public void loadEntity(Object oEnt){
        ent=((VideoupCatgs)oEnt);
        txCatg.setText(ent.getCatg());
        txDesc.setText(ent.getDcatg());
        txConds.setText(ent.getCondTx());
        lblTitle.setText(getTitle());
        changes=false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txCatg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txDesc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txConds = new javax.swing.JTextArea();

        jLabel1.setText("Nombre del genero:");

        jLabel2.setText("Descripcion:");

        jLabel3.setText("Condiciones de uso (vacio no aplica)");

        txConds.setColumns(20);
        txConds.setRows(5);
        jScrollPane1.setViewportView(txConds);

        javax.swing.GroupLayout mainContainLayout = new javax.swing.GroupLayout(mainContain);
        mainContain.setLayout(mainContainLayout);
        mainContainLayout.setHorizontalGroup(
            mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txCatg)
                    .addComponent(txDesc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        mainContainLayout.setVerticalGroup(
            mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txCatg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainContain;
    private javax.swing.JTextField txCatg;
    private javax.swing.JTextArea txConds;
    private javax.swing.JTextField txDesc;
    // End of variables declaration//GEN-END:variables
}
