/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.modsocios;

import com.videoup.controllers.Controller;
import com.videoup.entities.VideoupAutrz;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Pedro
 */
public class PAutrz extends javax.swing.JPanel implements DocumentListener{

    private VideoupAutrz persona;
    private Ficha fich;
    private Controller ctrl;
    private boolean changes;
    
    /**
     * Creates new form PAutrz
     */
    public PAutrz(VideoupAutrz persona, Ficha fich, Controller ctrl) {
        this.persona=persona;
        this.fich=fich;
        this.ctrl=ctrl;
        initComponents();
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/videoup/imgs/save.png")));
        txtNombre.getDocument().addDocumentListener(this);
        showData();
        changes=false;
    }
    
    private void showData(){
        txtNombre.setText(persona.getPname());
    }

    public boolean hasChanges(){
        return changes;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDel = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new java.awt.BorderLayout());

        btnDel.setText("X");
        btnDel.setToolTipText("Eliminar persona");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        add(btnDel, java.awt.BorderLayout.LINE_END);
        add(txtNombre, java.awt.BorderLayout.CENTER);

        btnUpdate.setToolTipText("Actualizar Nonbre");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String updName=txtNombre.getText().trim();
        if(updName.length()<7 || updName.length()>255){
            ctrl.showDialogErr("El nombre debe tener una longitud entre 7 y 255 caracteres");
            return;
        }
        persona.setPname(updName);
        changes=!fich.updateChildEntity(persona);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        fich.deleteChildEntity(persona,1);
    }//GEN-LAST:event_btnDelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
        changes=true;
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        changes=true;
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        changes=true;
    }
}
