/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.modsocios;

import com.videoup.entities.VideoupPuntos;
import java.text.DateFormat;
import java.util.Calendar;

/**
 *
 * @author Pedro
 */
public class Spuntos extends javax.swing.JPanel {

    private VideoupPuntos ent;
    private Ficha fich;
    
    /**
     * Creates new form Spuntos
     */
    public Spuntos(VideoupPuntos ent, Ficha fich){
        this.ent=ent;
        this.fich=fich;
        initComponents();
        showData();
    }

    private void showData(){
        DateFormat dteFrt=DateFormat.getDateInstance();
        Calendar cal=Calendar.getInstance();
        boolean used=(ent.getUsedOn()!=null);
        lblPuntos.setText("<html><u>"+(ent.getPuntos()+ent.getUsedPuntos())+"</u> puntos</html>");
        lblAsign.setText("<html>asignados en: "+dteFrt.format(ent.getAsigOn())+"</html>");
        lblVigen.setText("<html>vigentes hasta: "+dteFrt.format(ent.getVHasta())+"</html>");
        lblUsed.setText( (used?"<html><span style=\"color:red;\">"+ent.getUsedPuntos()+"</> usados, ultima vez: "+dteFrt.format(ent.getUsedOn())+"</html>":"") );
        btnDel.setVisible( cal.getTime().after(ent.getVHasta())||ent.getPuntos()==0 );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPuntos = new javax.swing.JLabel();
        lblAsign = new javax.swing.JLabel();
        lblVigen = new javax.swing.JLabel();
        lblUsed = new javax.swing.JLabel();
        btnDel = new javax.swing.JButton();

        lblPuntos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblPuntos.setText("Puntos");
        add(lblPuntos);

        lblAsign.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAsign.setText("Asignados En");
        add(lblAsign);

        lblVigen.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblVigen.setText("Vigentes hasta");
        add(lblVigen);

        lblUsed.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblUsed.setText("Usados en");
        add(lblUsed);

        btnDel.setText("X");
        btnDel.setToolTipText("Eliminar registro del historial");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        add(btnDel);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        fich.deleteChildEntity(ent,4);
    }//GEN-LAST:event_btnDelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JLabel lblAsign;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblUsed;
    private javax.swing.JLabel lblVigen;
    // End of variables declaration//GEN-END:variables
}
