/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.modctgpre;

import com.videoup.controllers.Controller;
import com.videoup.entities.VideoupBaseEntity;
import com.videoup.entities.VideoupCtprrentas;
import com.videoup.views.utils.ViewFicha;
import java.util.Currency;
import java.util.Locale;

/**
 *
 * @author Pedro
 */
public class Ficha extends ViewFicha{

    private VideoupCtprrentas ent;
    private Currency currency;
    
    /**
     * Creates new form Ficha
     */
    public Ficha(Controller ctrl, int id) {
        super(ctrl,id,true);
        initComponents();
        initComps(ent);
    }

    public Ficha(Controller ctrl, Object ent, int id) {
        super(ctrl,id,false);
        initComponents();
        initComps(ent);
    }
    
    @Override
    protected void loadEntity(int id){
        ent=(VideoupCtprrentas)getEntity("from VideoupCtprrentas where idcpr="+id);
    }
    
    private void initComps(Object ent){
        putMainContain(mainContain);
        currency=Currency.getInstance(Locale.getDefault());
        jLabel2.setText("Costo de alquiler "+currency.getSymbol()+":");
        jLabel6.setText("Costo tiempo extra "+currency.getSymbol()+":");
        if(ent==null){
            this.ent=new VideoupCtprrentas();
        }else{
            loadEntity(ent);
        }
        setUpValidator();
        addJText2ListenChanges(txNom);
        addJText2ListenChanges(txCostoU);
        addJText2ListenChanges(txTBase);
        addJText2ListenChanges(txCostoUXtra);
    }
    
    @Override
    protected void setUpValidator(){
        super.setUpValidator();
        vltor.addStringField(txNom, "Nombre de categoria", true, 5, 55,0);
        vltor.addDoubleField(txCostoU, "Costo tiempo normal", true, 1, 1000,0);
        vltor.addIntField(txTBase, "Tiempo base", true, 1, 1000,0);
        vltor.addDoubleField(txCostoUXtra, "Costo tiempo extra", true, 1, 1000,0);
    }
    
    @Override
    public String getTitle(){
        return "Ficha de Catalogo de costos alquileres "+(getId()==0?" nueva":(ent==null?" ID: "+getId():": "+ent.getNamec()));
    }
        
    @Override
    protected boolean saveEntity(VideoupBaseEntity ignore,boolean forceAsNew){
        int unmin=jcbUnidadT.getSelectedIndex();
        boolean saved;
        ent.setNamec(txNom.getText());
        ent.setCostou(Float.parseFloat(txCostoU.getText()));
        ent.setUnidadNm(jcbUnidadT.getSelectedItem().toString());
        ent.setUnsBase(Integer.parseInt(txTBase.getText()));
        ent.setCstuXtra(Float.parseFloat(txCostoUXtra.getText()));
        ent.setUnidadMins(unmin==0?60:1440);
        saved=super.saveEntity(ent,forceAsNew);
        changes=!saved;
        return saved;
    }
    
    @Override
    protected void updateIdTitle(){
        setId(ent.getIdcpr());
        lblTitle.setText(getTitle());
        ctrl.changeViewName(this, getTitle());
    }
    
    @Override
    public void loadEntity(Object oEnt){
        ent=((VideoupCtprrentas)oEnt);
        txNom.setText(ent.getNamec());
        txCostoU.setText(""+ent.getCostou());
        jcbUnidadT.setSelectedItem(ent.getUnidadNm());
        txTBase.setText(""+ent.getUnsBase());
        txCostoUXtra.setText(""+ent.getCstuXtra());
        lblTitle.setText(getTitle());
        changes=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txNom = new javax.swing.JTextField();
        txCostoU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txTBase = new javax.swing.JTextField();
        jcbUnidadT = new javax.swing.JComboBox();
        txCostoUXtra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("Nombre de categoria:");

        jLabel2.setText("Costo de alquiler:");

        jLabel3.setText("(Aplica por unidad de tiempo dentro del tiempo base)");

        jLabel4.setText("Unidad de tiempo:");

        jLabel5.setText("Tiempo base:");

        jLabel6.setText("Costo alquiler:");

        jcbUnidadT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hora", "Dia" }));
        jcbUnidadT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbUnidadTItemStateChanged(evt);
            }
        });

        jLabel7.setText("(Aplica por unidades de tiempo en tiempo extra)");

        javax.swing.GroupLayout mainContainLayout = new javax.swing.GroupLayout(mainContain);
        mainContain.setLayout(mainContainLayout);
        mainContainLayout.setHorizontalGroup(
            mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainContainLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txNom, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainContainLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCostoU, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainContainLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbUnidadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainContainLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txTBase, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainContainLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCostoUXtra, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainContainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        mainContainLayout.setVerticalGroup(
            mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txCostoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbUnidadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txTBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txCostoUXtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void jcbUnidadTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbUnidadTItemStateChanged
        changes=true;
    }//GEN-LAST:event_jcbUnidadTItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox jcbUnidadT;
    private javax.swing.JPanel mainContain;
    private javax.swing.JTextField txCostoU;
    private javax.swing.JTextField txCostoUXtra;
    private javax.swing.JTextField txNom;
    private javax.swing.JTextField txTBase;
    // End of variables declaration//GEN-END:variables
}
