/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.sys;

import com.vendors.utils.WrapLayout;
import java.awt.BorderLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Pedro
 */
public class ItemMnuExpnd extends javax.swing.JPanel {

    private String name;
    private ImageIcon logo;
    private Object[][] btns; // for row icon,tooltiptext,actioncommand
    private Videoup vUp;
    
    /**
     * Creates new form ItemMnuExpnd
     */
    public ItemMnuExpnd(Videoup vUp, String name,String ico,Object[][] btns){
        this.name=name;
        this.btns=btns;
        this.vUp=vUp;
        logo=new javax.swing.ImageIcon(getClass().getResource(ico));
        initComponents();
        reInitComponents();
    }

    private void reInitComponents(){
        JButton[] btnMatx = new JButton[btns.length];
        pnlBttns.setLayout(new WrapLayout());
        lblLogo.setIcon(logo);
        lblLogo.setText(null);
        lblName.setFont(new java.awt.Font("Tahoma",1,29)); 
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText(name);
        for(int x=0;x<btns.length;x++){
                btnMatx[x]=new JButton(); 
                btnMatx[x].setIcon( ((Icon)btns[x][0]) );
                btnMatx[x].setToolTipText(btns[x][1].toString());
                btnMatx[x].setActionCommand(btns[x][2].toString());
                btnMatx[x].addActionListener(vUp);
                pnlBttns.add(btnMatx[x]);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        pnlBttns = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));
        setMaximumSize(new java.awt.Dimension(292, 159));
        setMinimumSize(new java.awt.Dimension(292, 159));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("Logo");
        lblLogo.setOpaque(true);

        lblName.setFont(new java.awt.Font("Tahoma", 1, 29)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Nombre");

        pnlBttns.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        javax.swing.GroupLayout pnlBttnsLayout = new javax.swing.GroupLayout(pnlBttns);
        pnlBttns.setLayout(pnlBttnsLayout);
        pnlBttnsLayout.setHorizontalGroup(
            pnlBttnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBttnsLayout.setVerticalGroup(
            pnlBttnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBttns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlBttns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlBttns;
    // End of variables declaration//GEN-END:variables
}
