/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.sys;

import com.videoup.controllers.Controller;
import com.videoup.views.utils.ImagePanel;
import com.videoup.views.utils.ViewsSelector;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author Pedro
 */
public class OpenViewsMenuExpnd extends javax.swing.JPanel {

    private ViewsSelector vsel;
    
    /**
     * Creates new form OpenViewsMenuExpnd
     */
    public OpenViewsMenuExpnd() {
        BufferedImage img;
        Graphics g;
        ImagePanel imgp;
        ImageIcon icon;
        vsel=new ViewsSelector(null,"Vistas",new ImageIcon(getClass().getResource("/com/videoup/imgs/videoupIcon.png")));
        vsel.removeObtnNew();
        initComponents();
        icon=new ImageIcon(getClass().getResource("/com/videoup/imgs/mnuexp_cen.png"));
        img=new BufferedImage(icon.getIconWidth(),icon.getIconHeight(),BufferedImage.TYPE_INT_RGB);
        g=img.createGraphics();
        icon.paintIcon(null, g, 0,0);
        g.dispose();
        imgp=new ImagePanel(img);
        imgp.setRepeatV(true);
        imgp.setToolTipText("Vistas abiertas");
        imgp.setLayout(new BorderLayout());
        imgp.setToolTipText("Vistas abiertas");
        imgp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                swapViewSel();
            }
        });
        add(vsel,BorderLayout.CENTER);
        pnlBar.add(imgp,BorderLayout.WEST);
        vsel.setVisible(false);
    }
    
    private void swapViewSel(){
        boolean isVis=vsel.isVisible();
        vsel.setVisible(!isVis);
    }
    
    public void addOpenViewName(Controller ctl, String name, int key, boolean closable){
        vsel.addOption(ctl,name,key,closable);
    }

    public ViewsSelector getVsel() {
        return vsel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBar = new javax.swing.JPanel();
        lblEsqSup = new javax.swing.JLabel();
        lblEsqInf = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnlBar.setLayout(new java.awt.BorderLayout());

        lblEsqSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/videoup/imgs/mnuexp_esq_sup.png"))); // NOI18N
        lblEsqSup.setToolTipText("Vistas abiertas");
        lblEsqSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEsqSupMouseClicked(evt);
            }
        });
        pnlBar.add(lblEsqSup, java.awt.BorderLayout.PAGE_START);

        lblEsqInf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/videoup/imgs/mnuexp_esq_inf.png"))); // NOI18N
        lblEsqInf.setToolTipText("Vistas abiertas");
        lblEsqInf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEsqInfMouseClicked(evt);
            }
        });
        pnlBar.add(lblEsqInf, java.awt.BorderLayout.PAGE_END);

        add(pnlBar, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void lblEsqSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqSupMouseClicked
        swapViewSel();
    }//GEN-LAST:event_lblEsqSupMouseClicked

    private void lblEsqInfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqInfMouseClicked
        swapViewSel();
    }//GEN-LAST:event_lblEsqInfMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEsqInf;
    private javax.swing.JLabel lblEsqSup;
    private javax.swing.JPanel pnlBar;
    // End of variables declaration//GEN-END:variables
}

