/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.sys;

import com.vendors.utils.WrapLayout;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Pedro
 */
public class SearchMnuExpnd extends javax.swing.JPanel {

    private int typo; // 1=socios, 2=movies, 3=games
    private String[] ttext;
    private ImageIcon logo;
    private JButton btnBusca;
    private JTextField txtKey;
    private Videoup vUp;
    
    /**
     * Creates new form SearchMnuExpnd
     */
    public SearchMnuExpnd(Videoup vUp){
        this.vUp=vUp;
        typo=0;
        ttext=new String[]{"Indique codigo de socio, nombre, apellidos o DNI",
            "Indique codigo de barras, titulo",
            "Indique codigo de barras, titulo"
        };
        logo=new javax.swing.ImageIcon(getClass().getResource("/com/videoup/imgs/mBuscar.png"));
        initComponents();
        reInitComponents();
    }
    
    private void reInitComponents(){
        rbtnGrpTypo.add(rOptSoc);
        rOptSoc.setSelected(true);
        rOptSoc.setText("Socios");
        rOptSoc.setOpaque(false);
        rbtnGrpTypo.add(rOptMovies);
        rOptMovies.setText("Peliculas");
        rOptMovies.setOpaque(false);
        rbtnGrpTypo.add(rOptGames);
        rOptGames.setText("Video Juegos");
        rOptGames.setOpaque(false);
        rOptSoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateTypo();
            }
        });
        rOptMovies.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateTypo();
            }
        });
        rOptGames.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateTypo();
            }
        });
        txtKey=new JTextField(16);
        txtKey.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                    btnBusca.doClick();
                }
            }
        });
        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlBttns.setLayout(new WrapLayout());
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(logo);
        lblLogo.setText(null);
        lblName.setFont(new java.awt.Font("Tahoma",1,29)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Buscar");
        btnBusca=new JButton();
        btnBusca.setIcon( new ImageIcon(getClass().getResource("/com/videoup/imgs/buscar.png")) );
        btnBusca.setActionCommand("mnuexp_search");
        btnBusca.addActionListener(vUp);
        pnlBttns.add(txtKey);
        pnlBttns.add(btnBusca);
        updateTypo();
    }

    private void updateTypo(){
        typo=(rOptSoc.isSelected()?0:rOptMovies.isSelected()?1:2);
        if(txtKey!=null && ttext!=null && btnBusca!=null &&lblMsg!=null){
            lblMsg.setText(ttext[typo]);
            btnBusca.setToolTipText(ttext[typo]);
            txtKey.setToolTipText(ttext[typo]);
        }
    }  
    
    public int getTypo(){
        return typo;
    }
    
    public String getVal2Search(){
        return txtKey.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGrpTypo = new javax.swing.ButtonGroup();
        lblLogo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        pnlBttns = new javax.swing.JPanel();
        lblMsg = new javax.swing.JLabel();
        rOptSoc = new javax.swing.JRadioButton();
        rOptMovies = new javax.swing.JRadioButton();
        rOptGames = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("Logo");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 29)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Nombre");

        pnlBttns.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));

        javax.swing.GroupLayout pnlBttnsLayout = new javax.swing.GroupLayout(pnlBttns);
        pnlBttns.setLayout(pnlBttnsLayout);
        pnlBttnsLayout.setHorizontalGroup(
            pnlBttnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );
        pnlBttnsLayout.setVerticalGroup(
            pnlBttnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMsg.setText("mensaje");

        rbtnGrpTypo.add(rOptSoc);
        rOptSoc.setSelected(true);
        rOptSoc.setText("Socios");
        rOptSoc.setOpaque(false);

        rbtnGrpTypo.add(rOptMovies);
        rOptMovies.setText("Peliculas");

        rbtnGrpTypo.add(rOptGames);
        rOptGames.setText("Video Juegos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(rOptSoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rOptMovies)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rOptGames)
                                .addGap(0, 42, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlBttns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rOptSoc)
                            .addComponent(rOptMovies)
                            .addComponent(rOptGames)))
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBttns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlBttns;
    private javax.swing.JRadioButton rOptGames;
    private javax.swing.JRadioButton rOptMovies;
    private javax.swing.JRadioButton rOptSoc;
    private javax.swing.ButtonGroup rbtnGrpTypo;
    // End of variables declaration//GEN-END:variables
}
