/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.modbonos;

import com.videoup.controllers.Controller;
import com.videoup.entities.VideoupBaseEntity;
import com.videoup.entities.VideoupBonos;
import com.videoup.views.utils.ViewFicha;
import java.util.Currency;
import java.util.Locale;

/**
 *
 * @author Pedro
 */
public class Ficha extends ViewFicha{

    private VideoupBonos ent;

    /**
     * Creates new form Ficha
     */
    public Ficha(Controller ctrl, int id) {
        super(ctrl,id, true);
        initComponents();
        initComps(ent);
    }

    public Ficha(Controller ctrl, Object ent, int id) {
        super(ctrl,id,false);
        initComponents();
        initComps(ent);
    }
    
    @Override
    protected void loadEntity(int id){
        ent=(VideoupBonos)getEntity("from VideoupBonos where idbn="+id);
    }
    
    private void initComps(Object ent){
        Currency currency=Currency.getInstance(Locale.getDefault());
        putMainContain(mainContain);
        if(ent==null){
            this.ent=new VideoupBonos();
        }else{
            loadEntity(ent);
        }
        lblPrecio.setText("Precio "+currency.getSymbol()+": ");
        setUpValidator();
        addJText2ListenChanges(txArts);
        addJText2ListenChanges(txDias);
        addJText2ListenChanges(txHours);
        addJText2ListenChanges(txPrecio);
    }
    
    @Override
    protected void setUpValidator(){
        super.setUpValidator();
        vltor.addIntField(txArts, "Numero de Bonos", true, 1, 999, 0);
        vltor.addIntField(txHours, "Horas por Bono", true, 1, 50, 0);
        vltor.addIntField(txDias, "Vigencia en dias", true, 0, 9999, 0);
        vltor.addDoubleField(txPrecio, "Precio", true, 1, 999, 0);
    }

    @Override
    public String getTitle(){
        return "Ficha de bono"+(getId()==0?" nueva":(ent==null?" ID: "+getId():": "+ent.toString()));
    }
    
    @Override
    protected boolean saveEntity(VideoupBaseEntity ignore,boolean forceAsNew){
        boolean saved;
        ent.setDias( Integer.parseInt(txDias.getText()) );
        ent.setArticls( Integer.parseInt(txArts.getText()) );
        ent.setHours( Integer.parseInt(txHours.getText()) );
        ent.setApplygms(jckGames.isSelected());
        ent.setApplymvs(jckMovs.isSelected());
        ent.setCosto( Float.parseFloat(txPrecio.getText()) );
        saved=super.saveEntity(ent,forceAsNew);
        changes=!saved;
        return saved;
    }
    
    @Override
    protected void updateIdTitle(){
        setId(ent.getIdbn());
        lblTitle.setText(getTitle());
        ctrl.changeViewName(this, getTitle());
    }
    
    @Override
    public void loadEntity(Object oEnt){
        ent=((VideoupBonos)oEnt);
        txDias.setText(""+ent.getDias());
        txArts.setText(""+ent.getArticls());
        txHours.setText(""+ent.getHours());
        jckGames.setSelected(ent.isApplygms());
        jckMovs.setSelected(ent.isApplymvs());
        txPrecio.setText(""+ent.getCosto());
        lblTitle.setText(getTitle());
        changes=false;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txArts = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jckMovs = new javax.swing.JCheckBox();
        jckGames = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txDias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txHours = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txPrecio = new javax.swing.JTextField();

        jLabel1.setText("Numero de bonos:");

        txArts.setColumns(6);

        jLabel2.setText("Aplica a:");

        jckMovs.setText("Peliculas");

        jckGames.setText("Juegos");

        jLabel3.setText("Vigencia del paquete:");

        txDias.setColumns(6);

        jLabel4.setText("dias");

        jLabel5.setText("Cada bono es por:");

        txHours.setColumns(6);

        jLabel6.setText("horas");

        lblPrecio.setText("Precio:");

        txPrecio.setColumns(8);

        javax.swing.GroupLayout mainContainLayout = new javax.swing.GroupLayout(mainContain);
        mainContain.setLayout(mainContainLayout);
        mainContainLayout.setHorizontalGroup(
            mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainLayout.createSequentialGroup()
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainContainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txArts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainContainLayout.createSequentialGroup()
                                .addComponent(txHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(mainContainLayout.createSequentialGroup()
                                .addComponent(txDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(txPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainContainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jckMovs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jckGames)))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        mainContainLayout.setVerticalGroup(
            mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jckMovs)
                    .addComponent(jckGames))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txArts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JCheckBox jckGames;
    private javax.swing.JCheckBox jckMovs;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JPanel mainContain;
    private javax.swing.JTextField txArts;
    private javax.swing.JTextField txDias;
    private javax.swing.JTextField txHours;
    private javax.swing.JTextField txPrecio;
    // End of variables declaration//GEN-END:variables
}
