/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.videoup.views.modbonos;

import com.videoup.entities.VideoupBonos;
import com.videoup.entities.VideoupSoldBonos;

/**
 *
 * @author Pedro
 */
public class SellingBono extends javax.swing.JPanel {

    private SellBonos seller;
    private VideoupBonos bono;
    VideoupSoldBonos soldBono;
    
    /**
     * Creates new form SellingBono
     */
    public SellingBono(SellBonos seller, VideoupBonos bono){
        this.seller=seller;
        this.bono=bono;
        this.soldBono=null;
        initComponents();
        lblDesc.setText(bono.getExtDescrip());
    }
    
    public SellingBono(VideoupSoldBonos bono){
        this.seller=null;
        this.bono=null;
        this.soldBono=bono;
        initComponents();
        jckSelected.setEnabled(false);
        jckSelected.setVisible(false);
        lblDesc.setText(soldBono.getExtDescrip());
    }

    public float getCosto(){
        return (jckSelected.isSelected()?bono.getCosto():0);
    }
    
    public int getDays(){
        return bono.getDias();
    }
    
    public int getBonos(){
        return bono.getArticls();
    }
    
    public int getHours(){
        return bono.getHours();
    }
    
    public boolean getApplyMovs(){
        return bono.isApplymvs();
    }
    
    public boolean getApplyGms(){
        return bono.isApplygms();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jckSelected = new javax.swing.JCheckBox();
        lblDesc = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jckSelected.setToolTipText("Agregar bono");
        jckSelected.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jckSelectedItemStateChanged(evt);
            }
        });
        add(jckSelected, java.awt.BorderLayout.LINE_START);

        lblDesc.setText("Descripcion del bono");
        add(lblDesc, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jckSelectedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jckSelectedItemStateChanged
        seller.updateTotals();
    }//GEN-LAST:event_jckSelectedItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jckSelected;
    private javax.swing.JLabel lblDesc;
    // End of variables declaration//GEN-END:variables
}
